version: '3.4'
services:
  queue:
    image: rabbitmq:3.7.0-management
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    hostname: paperboy_queue
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: Boo4bah3ohcohthaeHa5ohter0iSeeS0
    ports:
      - "15672:15672"
      - "5672:5672"
  push-service:
    build:
      context: paperboy-push-service
      target: development
    environment:
      QUEUE_URI: amqp://admin:Boo4bah3ohcohthaeHa5ohter0iSeeS0@queue:5672
      QUEUE_EXCHANGE: paperboy,paperboy_preview
      API_TOKEN: eash9uk3eejak6ena7thi8DooMih5eax
    ports:
      - "8081:8080"
    depends_on:
      - queue
    volumes:
      - ./paperboy-push-service/src:/home/node/src:ro,consistent