version: '3.4'
services:
  queue:
    image: rabbitmq:3.7.14-management
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    hostname: paperboy_queue
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "15672:15672"
      - "5672:5672"
  push-service:
    build:
      context: paperboy-push-service
      target: development
    ports:
      - "8081:8080"
    depends_on:
      - queue
    volumes:
      - ./paperboy-push-service/src:/home/node/app/src:ro,consistent